config/routes.rb
require "resque/server"

Bountyhill::Application.routes.draw do
  opinio_model

  app = Rack::Builder.new {
    use ::AdminOnlyMiddleware
    run Resque::Server.new
  }.to_app

  mount app, :at => "/jobs"

  %w(faq contact imprint terms privacy).each do |static_page|
    match static_page => "static##{static_page}", :via => :get
  end

  %w(quests offers).each do |images_container|
    match "/#{images_container}/:id/lightbox/:active"  => "#{images_container}#lightbox", :via => :get
  end

  resources :quests do
    opinio
  end
  match "/q/:id"                      => "quests#show",   :via => :get
  match "/quests/category/:category"  => "quests#index",  :via => :get
  match "/quests/:owner_id/list"      => "quests#index",  :via => :get
  
  resources :shares
  
  resources :runs
  match "/runs/:id"         => "runs#update", :via => :post
  match "/runs/:id/start"   => "runs#start",  :via => :get
  match "/runs/:id/cancel"  => "runs#cancel", :via => :get
  
  resources :offers do
    opinio
    member do
      get "activate"
      put "activate"
      get "accept"
      put "accept"
      get "reject"
      put "reject"
      get "withdraw"
      put "withdraw"
    end
  end
  match "/offers/:owner_id/list" => "offers#index",  :via => :get

  resources :users
  match 'profile'           => "users#show",    :via => :get
  match "/users/:id/delete" => "users#delete",  :via => :get

  resources :activities
  
  resources :messages
  
  resources :sessions
  match "signin"          => "sessions#signin_get",     :via => :get
  match "signin"          => "sessions#signin_post",    :via => :post
  match "signup"          => "sessions#signin_post",    :via => :post
  match "signout"         => "sessions#destroy",        :via => :delete
  match "sessions/cancel" => "sessions#cancel",         :via => :post
  
  resources :identities do 
    member do
      get "delete"
      get "init"
      get "failure"
      post "success"
    end
  end

  match 'auth/:provider/init'     => 'identities#init'
  match 'auth/:provider/callback' => 'identities#success'
  match 'auth/failure'            => 'identities#failure'

  resources :deferred_actions, :only => [:show]
  match 'act'             => 'deferred_actions#show'
  match 'confirm'         => 'deferred_actions#confirm'
  match 'reset_password'  => 'deferred_actions#reset_password'
  
  
  match '/404' => 'errors#not_found'
  match '/422' => 'errors#unprocessable_entity'
  match '/500' => 'errors#internal_server_error'

  root :to => 'home#index'

end

app/controllers/quests_controller.rb
# encoding: UTF-8

class QuestsController < ApplicationController
  include ApplicationController::ImageInteractions
  include Filter::Builder

  before_filter :set_owner
  
  # GET /quests
  def index
    # init quest scope
    scope = if params[:owner_id] then User.find(params[:owner_id]).quests
            else                      Quest.active
            end
    
    # init location
    @location = Location.new(location_attrs)
    
    # set additional location scope
    scope = scope.nearby(@location.address, @location.radius) unless @location.unlimited?
    
    # set additional category scope
    @filters = filters_for(scope, :category)
    scope = scope.with_category(params[:category]) if params[:category].present?
    
    # fetch quests
    @quests = scope.paginate(
      :page       => params[:page] ||= 1,
      :per_page   => per_page,
      :group      => 'quests.id',
      :order      => "quests.created_at desc",
      :include    => [{ :owner => :identities }, :location, :comments, :offers])
  end

  # GET /quests/1
  def show
    # fetch the requested quest first
    # when current user is not known, it could be also a draft quest
    @quest = Quest.find_by_id(params[:id]) || Quest.draft(params[:id])

    return render :action => "preview" if params[:preview] # intending to be started (preview param is passed in this case)
  end

  def new
    @quest ||= Quest.new
    @quest.bounty_in_cents = Quest::DEFAULT_BOUNTY
    @quest.build_location(location_attrs)
  end

  def edit
    @quest = Quest.find(params[:id])

    # init location
    if @quest.location.present? then  @quest.restrict_location = true
    else                              @quest.build_location(location_attrs)
    end
    
    render :action => "new"
  end

  # POST /quests
  def create
    @quest = Quest.new(params[:quest])
    @quest.owner ||= User.draft
    
    # remove location if it's not given or not valid
    @quest.location = nil unless @quest.restrict_location?
    
    # Show start quest form after successful saving.
    if @quest.save
      flash[:success] = I18n.t("notice.create.success", :record => Quest.model_name.human)
      redirect_to! quest_path(@quest, :preview => true)
    end

    render :action => "new"
  end
  
  # PUT /quests/1
  def update
    @quest = Quest.find(params[:id])
    @quest.attributes = params[:quest]
    
    # remove location if user wants to
    unless @quest.restrict_location?
      @quest.location.mark_for_destruction if @quest.location.present?
    end
    
    if @quest.valid?
      @quest.save!
      flash[:success] = I18n.t("notice.update.success", :record => Quest.model_name.human)
      redirect_to! quest_path(@quest)
    end

    render :action => "new"
  end

  # DELETE /quests/1
  def destroy
    @quest = Quest.find(params[:id])
    @quest.destroy

    redirect_to quests_url
  end
  
private
  def set_owner
    @owner = User.find(params[:owner_id]) if params[:owner_id]
  end

  def location_attrs
    # when user filters by location, :location param is present
    return params[:location] if params[:location].present?

    # if user has a location as an address given we consider this one
    # otherwise we try to get the location from the current request
    address = if    current_user && current_user.location then  current_user.location
              elsif request && request.location           then  request.location.name
              end.to_s

    { :radius => 'unlimited', :address => address }
  end
end

app/helpers/quests_helper.rb
# encoding: UTF-8

module QuestsHelper

  def quest_box(quest, options={})
    expect! quest => Quest
    
    title = I18n.t("quest.box.title", :amount => number_to_currency(quest.bounty, :precision => 0, :unit => '€'))
    box(:quest, quest, { :title => title, :time => quest_duration(quest) }.merge(options))
  end

  def quests_list_box(quests, options={})
    expect! quests        => ActiveRecord::Relation
    expect! quests.first  => [Quest, nil]
    expect! options       => Hash
    
    options[:filter] = I18n.t("quest.categories.#{options[:filter]}") if options[:filter]
    
    list_box(:quests, quests, options)
  end
  
  def new_quest_button
    awesome_button(icon_for('interaction.new'), new_quest_path) { I18n.t("nav.start_quest") }
  end

  def categories_select_options
    Quest::CATEGORIES.inject([]) do |options, category|
      options << [I18n.t(category, :scope => "quest.categories"), category]
    end
  end
  
  def location_radius_select_options(radius)
    expect! radius => (Location::RADIUS.dup << nil)
    radius ||= 'unlimited'
    
    options_for_select(
      Location::RADIUS.inject([]) do |options, r|
        options <<  if Location.unlimited?(r) then  [I18n.t('unlimited', :scope => "location.radius"),               r]
                    else                            [I18n.t('limited',   :scope => "location.radius", :radius => r), r]
                    end
      end, radius)
  end
  
  def quests_location_filter(location)
    expect! location => [Location, nil]
    
    header = div :class => "header" do
      div(I18n.t("filter.location.title"), :class => "pull-left")
    end

    content = div :class => "content" do
      partial("shared/location", :url => quests_path, :location => location)
    end
    
    div :class => "quest location filter box row-fluid" do
      header + content
    end
  end
  
  def quests_category_filters(filters=[])
    filter_box(:quest, :categories, filters, :title => I18n.t("filter.categories.title"), :active => params[:category], :class => "category")
  end
  
  def quest_buttons(quest)
    button_group [
      contact_owner_button(quest),
      share_quest_button(quest),
      new_offer_button(quest),
      stop_quest_button(quest),
      edit_quest_button(quest),
      start_quest_button(quest)
    ]
  end
  
  def share_quest_button(quest)
    return unless quest.active?

    modal_awesome_button(icon_for('interaction.share'), new_share_path(:quest_id => quest)) { I18n.t("button.share") }
  end

  def new_offer_button(quest)
    return unless quest.active?
    return if current_user && current_user.owns?(quest)

    awesome_button(icon_for('interaction.offer'), new_offer_path(:quest_id => quest)) { I18n.t("button.offer") }
  end

  def start_quest_button(quest, options={})
    return if quest.active?
    
    # Check if the user owns quest or if
    # the quest was created by a public user
    if current_user then  return unless current_user.owns?(quest)
    else                  return unless User.draft.owns?(quest)
    end
    
    modal_awesome_button(icon_for('interaction.start'), run_path(quest), options) { I18n.t("button.start") }
  end

  def stop_quest_button(quest)
    return unless current_user
    return unless quest.active? && current_user.owns?(quest)

    modal_awesome_button(icon_for('interaction.stop'), url_for(:controller => :runs, :action => :cancel, :id => quest)) { I18n.t("button.stop") }
  end
  
  def edit_quest_button(quest)
    return unless current_user
    return unless !quest.active? && current_user.owns?(quest)

    awesome_button(icon_for('interaction.edit'), edit_quest_path(quest)) { I18n.t("button.edit") }
  end

  def quest_statistic(quest)
    statistic_entries = []

    statistic_entries << 
      if    quest.active?   then awesome_icon(icon_for('other.bounty'))   + number_to_currency(quest.bounty, :precision => 0, :unit => '€').html_safe
      elsif quest.expired?  then awesome_icon(icon_for('status.expired')) + I18n.t('quest.status.expired')
      elsif !quest.started? then awesome_icon(icon_for('status.new'))     + I18n.t('quest.status.not_started')
      end

    statistic_entries << awesome_icon(icon_for('other.location'))  + quest.location.address                                    if quest.location.present?
    statistic_entries << awesome_icon(icon_for('other.picture'))   + I18n.t('quest.list.images', :count => quest.images.size)  if quest.images.present?
    statistic_entries.flatten

    ul :class => "stats-list" do
      statistic_entries.map{ |entry| li(entry) }.join.html_safe
    end
  end
  
  def quest_responses(quest)
    responses = []
    comments  = quest.comments.size
    offers    = quest.offers.for_user(current_user).size
    
    responses << circle_link_to(comments, quest_path(quest, :anchor => 'comments'),
      :class  => 'comments',
      :id     => "comments-#{dom_id(quest)}",
      :title  => I18n.t("quest.info.comments", :count => comments)) unless comments.zero?

    responses << circle_link_to(offers, quest_path(quest, :anchor => 'offers'),
      :class  => 'offers',
      :id     => "offers-#{dom_id(quest)}",
      :title  => I18n.t("quest.info.offers", :count => offers)) unless offers.zero?
    
    div :class => 'responses' do
      responses.map{ |response| response }.join.html_safe
    end unless responses.blank?
  end
  
  def quest_statistic_boxes(quest)
    [
      quest_bounty_statistic_box(quest),
      quest_days_statistic_box(quest),
      quest_offers_statistic_box(quest),
      quest_comments_statistic_box(quest),
      quest_forwards_statistic_box(quest)
    ].compact.map{ |box| box + spacer }.join.html_safe
  end

  def quest_days_statistic_box(quest)
    days, translation = if quest.active?
        if quest.expires? 
          [distance_of_time_in_days_to_now(quest.expires_at), "quest.statistic.expiration"]
        else
          [0, "quest.statistic.expiration"]
        end
      else
        [distance_of_time_in_days_to_now(quest.created_at), "quest.statistic.creation"]
      end
    statistic_box days.zero? ? '∞' : days,
      I18n.t(translation, :count => days),
      awesome_icon(icon_for('status.created')), :css_class => "quest"
  end
  
  def quest_bounty_statistic_box(quest)
    statistic_box number_to_currency(quest.bounty, :precision => 0, :unit => '€'),
      I18n.t("quest.statistic.bounty"),
      awesome_icon(icon_for('other.bounty')), :css_class => "quest"
  end
  
  def quest_offers_statistic_box(quest)
    statistic_box quest.offers.count,
      I18n.t("quest.statistic.offers", :count => quest.offers.count),
      awesome_icon(icon_for('status.offers')), :css_class => "quest"
  end

  def quest_comments_statistic_box(quest)
    statistic_box quest.comments.count,
      I18n.t("quest.statistic.comments"),
      awesome_icon(icon_for('status.comments')), :css_class => "quest"
  end
  
  def quest_forwards_statistic_box(quest)
    return if quest.forwards.size.zero?
    
    statistic_box quest.forwards.size,
      I18n.t("quest.statistic.forwards"),
      awesome_icon(icon_for('status.forwards')), :css_class => "quest"
  end
  
  def quest_duration(quest)
    expect! quest => Quest
    if quest.active?
      if quest.expires?
        I18n.t("quest.list.expiration", :distance_of_time => distance_of_time_in_words_to_now(quest.expires_at))
      else
        I18n.t("quest.list.no_expiration")
      end
    else
      I18n.t("quest.list.creation", :distance_of_time => distance_of_time_in_words_to_now(quest.created_at))
    end
    
  end
  
end

app/views/quests/_cell.html.erb
<div class="quest-cell no-flicker">
  <div class="tape"></div>
  <%= render_bounty_badge quest %>
  <div class="inner">
    <%= link_to user_path(quest.owner), :class => "profile" do %>
      <%= avatar quest.owner, :size => 64 %>
      <div class="handle">
        <%= quest.owner.twitter_handle %></br>
        <strong><%= quest.owner.name %></strong>
      </div>
    <% end %>
    
    <%= link_to quest_path(quest), :class => "request" do %>
      <%= h2(truncate(quest.title, :length => 100)) %>
    <% end %>
    
    <div class="restrictions">
      <%= render_restriction quest, :expires_at %>
      <%#= render_restriction quest, :location %>
    </div>
    
    <div class="socialmedia">
      <%= link_to "t", share_path(quest), :title => t("quest.actions.tweet.title"), :class => "social-item twitter", :rel => "nofollow" %>
    </div>
  </div>
</div>

app/views/quests/_form.html.erb
<%
  bounty  = @quest.bounty.to_s(:currency => false, :thousands_separators => false, :cents => false)
%>

<%= form_for @quest do |form| %>
  <p class="legend"><%= i18n_legend_for(@quest, :count => Quest::NUMBER_OF_CRITERIA) %></p>
  <%= form.error_messages %>

  <%= form.control_group :bounty, :text_field, :type => :number, :class => "input-small", :unit => "€", :value => bounty, :autocomplete => "off" %>
  <%= form.control_group :category,     :select,    :select_options => categories_select_options %>
  <%= form.control_group :title,        :text_area, :rows => 2 %>
  <%= form.control_group :description,  :text_area, :rows => 6, :class => "tinymce" %>
  
  <div class="criteria">
    <% Quest.criteria_titles.each_with_index do |name, idx| %>
      <div class="criterium-group">
        <%= form.control_group name, :text_area, :rows => 2, :hint => I18n.t("quest.form.field_hint.criteria") %>
        <%#= form.control_group Quest.criteria_descriptions[idx], :text_area, :rows => 3, :hint => I18n.t("quest.form.field_hint.criteria_description") %>
      </div>
    <% end %>
  </div>
  
  <%= form.control_group :images, :filepicker, :multiple => true %>
  
  <%= form.control_group :duration_in_days, :radio_button, :hint => false do
      Quest::DURATIONS_IN_DAYS.map do |value|
        label :class => "radio" do
          form.radio_button(:duration_in_days, value, :checked => ((@quest.duration_in_days || Quest::DEFAULT_DURATION_IN_DAYS).to_i == value)) +
          I18n.t('quest.form.field_hint.duration', :count => value)
        end
      end.join.html_safe
  end %>
  
  <div class="location">
    <%= form.restrict_location %>
    <div id="location_fields" class="<%= @quest.restrict_location? ? '' : 'hide' %>">
      <%= form.fields_for(:location, @quest.location) do |location_form| %>
        <%= partial 'locations/form', :form => location_form %>
      <% end %>
    </div>
  </div>
  
  <%= form.actions quests_path %>
<% end %>

<script type="text/javascript" charset="utf-8">
  // toggles location restriction
  $("#quest_restrict_location").change(function() {
    if($(this).is(':checked')) {
      $("#location_fields").slideDown('hide');
      google.maps.event.trigger(map, 'resize');
      marker.setPosition(map.getCenter());
    } else {
      $("#location_fields").slideUp('hide');
    }
  });
  <% if @quest.restrict_location? %>
    $("#quest_restrict_location").trigger('click');
  <% end %>


  (function($) {
    /*
        Hide all criterium groups that have no value in its input 
        nodes except the first one.
     */
    var count = 0;
    $(".criterium-group").each(function() {
      // array with true entries when there is input.
      var inputsHaveVals = jQuery.map($("textarea", this), function(input) {
        return $(input).val() !== "" ? true : false;
      });

      var visible = (jQuery.inArray(true, inputsHaveVals) != -1) ||
        (count++ == 0);

      if(!visible)
        $(this).hide();
    });
    
    /*
        Whenever a criterium grou gets focus we are showing the next 
        criterium group already: the user might want to enter some data
        there.
     */
    $(".criterium-group textarea").focus(function() {
      $(this).closest(".criterium-group").
        next(".criterium-group").show();
    });
    
  })(jQuery);
</script>

<%= tinymce %>

app/views/quests/_list.html.erb
<% @quests.each do |quest| %>
  <li class="quest" id="<%= dom_id(quest) %>">
    <%= partial "list_item", :quest => quest %>
  </li>
<% end %>

app/views/quests/_list_item.html.erb
<div class="message-container row-fluid">
  <%= link_to quest_path(quest), :class => "message-box span8" do %>
    <div class="message row-fluid">
      <div class="avatar-container span2">
        <%= avatar quest.owner, :size => 96 %>
      </div>
      <div class="text-container span10">
        <div class="message-head row-fluid">
          <div class="owner span6">
            <%= quest.owner.name %>
          </div>
          <div class="time span6">
            <%= quest_duration(quest) %>
          </div>
        </div>
        <div class="message-body">
          <%= truncate(quest.title, :length => 200) %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="message-stats span4">
    <%= quest_statistic(quest) %>
    <%= quest_responses(quest) %>
    <%= quest_buttons(quest) %>
  </div>
</div>

app/views/quests/_show.html.erb
<h1 itemprop="name"><%= quest.title %></h1>
<div itemprop="description" class="description"><%= quest.description.html_safe %></div>

<% if quest.criteria.present? %>
  <h2><%= I18n.t("quest.box.criteria", :count => quest.criteria.count) %></h2>
  <%= partial "shared/criteria", :container => quest, :complience => false %>
<% end %>

<% if quest.images.present? %>
  <h2><%= I18n.t("quest.box.images", :count => quest.images.count) %></h2>
  <img itemprop="image" style="display:none" src="<%= quest.images.first %>"/>
  <%= partial "shared/images", :container => quest %>
<% end %>

<% if quest.location.present? %>
  <h2><%= I18n.t("quest.box.location") %></h2>
  <%= partial "locations/show", :location => quest.location %>
<% end %>

<% if preview %>
  <div class="button-section">
    <%= start_quest_button(quest, :button => "btn btn-link", :size => "default") %>
  </div>
  <div class="clearfix"/>
<% end %>

app/views/quests/_sidebar.html.erb
<div class="side quest box">
  <%= link_to user_path(quest.owner) do
    avatar(quest.owner, :size => 32) +
    div(quest.owner.name, :class => "user")
  end %>
  
  <%= link_to quest_path(quest), :class => "title" do
    truncate(quest.title, :length => 200)
  end %>
  
  <div class="time">
    <%= quest_duration(quest) %>
  </div>
</div>

app/views/quests/_topbar.html.erb
<div class="quest topbar">
  <div class="image-container">
    <%= link_to user_path(quest.owner), :class => "owner" do
      avatar quest.owner, :size => 64
    end %>
  </div>
  <%= link_to quest_path(quest), :class => "bar-box" do %>
    <div class="bar-head">
      <div class="owner"><%= quest.owner.name %></div>
      <div class="time">
        <%= quest_duration(quest) %>
      </div>
    </div>
    <div class="bar-body">
      <div class="title"><%= quest.title %></div>
    </div>
  <% end %>
</div>

app/views/quests/index.html.erb
<div class="row-fluid">
  <div class="sidebar span3">
    <%= quests_location_filter(@location) %>
    <%= quests_category_filters(@filters) %>
  </div>
  <div class="main span9">
    <%= quests_list_box(@quests, :location => @location, :filter => params[:category] ) %>
  </div>
</div>

app/views/quests/index.js.erb
<% if @quests.total_pages > @quests.current_page -%>
$('ul.quests').append('<%= escape_javascript(render(partial: 'list')) %>');
$('a.endless_scroll_hook').attr('href', '<%= quests_path(params.merge(:page => (params[:page].to_i + 1))) %>').show();
<% else -%>
$('a.endless_scroll_hook').hide();
<% end -%>

app/views/quests/new.html.erb
<div class="row-fluid main">
  <div class="main span12">
    <%= form_box(@quest) %>
  </div>
</div>

app/views/quests/preview.html.erb
<div class="row-fluid main">
  <div class="span2">&nbsp;</div>
  <div class="main span8">
    <%= quest_box(@quest, :preview => true) %>
  </div>
  <div class="span2">&nbsp;</div>
</div>

app/views/quests/show.html.erb
<div class="row-fluid">
  <div class="main span9">
    <%= user_bar(@quest.owner, :quest) %>
  </div>
  <div class="sidebar empty span3">&nbsp;</div>
</div>
<%= spacer %>
<div class="row-fluid main">
  <div class="main span9">
    <%= quest_box(@quest, :class => "with-opener") %>
    <% if @quest.offers.for_user(current_user).any? %>
      <a id ='offers'></a>
      <%= spacer %>
      <%= offers_box(@quest, :class => "with-opener") %>
    <% end %>
    <a id ='comments'></a>
    <%= spacer %>
    <%= comments_box(@quest) %>
  </div>
  <div class="sidebar span3">
    <%= quest_statistic_boxes(@quest) %>
  </div>
</div>