config/routes.rb
require "resque/server"

Bountyhill::Application.routes.draw do
  opinio_model

  app = Rack::Builder.new {
    use ::AdminOnlyMiddleware
    run Resque::Server.new
  }.to_app

  mount app, :at => "/jobs"

  %w(faq contact imprint terms privacy).each do |static_page|
    match static_page => "static##{static_page}", :via => :get
  end

  %w(quests offers).each do |images_container|
    match "/#{images_container}/:id/lightbox/:active"  => "#{images_container}#lightbox", :via => :get
  end

  resources :quests do
    opinio
  end
  match "/q/:id"                      => "quests#show",   :via => :get
  match "/quests/category/:category"  => "quests#index",  :via => :get
  match "/quests/:owner_id/list"      => "quests#index",  :via => :get
  
  resources :shares
  
  resources :runs
  match "/runs/:id"         => "runs#update", :via => :post
  match "/runs/:id/start"   => "runs#start",  :via => :get
  match "/runs/:id/cancel"  => "runs#cancel", :via => :get
  
  resources :offers do
    opinio
    member do
      get "activate"
      put "activate"
      get "accept"
      put "accept"
      get "reject"
      put "reject"
      get "withdraw"
      put "withdraw"
    end
  end
  match "/offers/:owner_id/list" => "offers#index",  :via => :get

  resources :users
  match 'profile'           => "users#show",    :via => :get
  match "/users/:id/delete" => "users#delete",  :via => :get

  resources :activities
  
  resources :messages
  
  resources :sessions
  match "signin"          => "sessions#signin_get",     :via => :get
  match "signin"          => "sessions#signin_post",    :via => :post
  match "signup"          => "sessions#signin_post",    :via => :post
  match "signout"         => "sessions#destroy",        :via => :delete
  match "sessions/cancel" => "sessions#cancel",         :via => :post
  
  resources :identities do 
    member do
      get "delete"
      get "init"
      get "failure"
      post "success"
    end
  end

  match 'auth/:provider/init'     => 'identities#init'
  match 'auth/:provider/callback' => 'identities#success'
  match 'auth/failure'            => 'identities#failure'

  resources :deferred_actions, :only => [:show]
  match 'act'             => 'deferred_actions#show'
  match 'confirm'         => 'deferred_actions#confirm'
  match 'reset_password'  => 'deferred_actions#reset_password'
  
  
  match '/404' => 'errors#not_found'
  match '/422' => 'errors#unprocessable_entity'
  match '/500' => 'errors#internal_server_error'

  root :to => 'home#index'

end

app/controllers/home_controller.rb
# encoding: UTF-8

class HomeController < ApplicationController
  
  def index
  end
  
end

app/views/home/index.html.erb
<div class="row-fluid">
  <div class="span12">
    <div class="explanation">
      <% (1..5).each do |index| %>
        <div class="item item<%= index %>">
          <div class="headline"><%= I18n.t("home.explanation.headline#{index}").html_safe %></div>
          <div class="text"><%= I18n.t("home.explanation.text#{index}").html_safe %></div>
          <%= image_tag asset_path("home/key_0#{index}.png") %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="row-fluid">
  <div class="span12">
    <div class="claim">
      <%= link_to quests_path, :class => 'logo' do %>
        <span class='main'>bountyhill</span><br>
        <span class='sub'><%= I18n.t("home.claim")%></span>
      <% end %>
    </div>
  </div>
</div>