config/routes.rb
require "resque/server"

Bountyhill::Application.routes.draw do
  opinio_model

  app = Rack::Builder.new {
    use ::AdminOnlyMiddleware
    run Resque::Server.new
  }.to_app

  mount app, :at => "/jobs"

  %w(faq contact imprint terms privacy).each do |static_page|
    match static_page => "static##{static_page}", :via => :get
  end

  %w(quests offers).each do |images_container|
    match "/#{images_container}/:id/lightbox/:active"  => "#{images_container}#lightbox", :via => :get
  end

  resources :quests do
    opinio
  end
  match "/q/:id"                      => "quests#show",   :via => :get
  match "/quests/category/:category"  => "quests#index",  :via => :get
  match "/quests/:owner_id/list"      => "quests#index",  :via => :get
  
  resources :shares
  
  resources :runs
  match "/runs/:id"         => "runs#update", :via => :post
  match "/runs/:id/start"   => "runs#start",  :via => :get
  match "/runs/:id/cancel"  => "runs#cancel", :via => :get
  
  resources :offers do
    opinio
    member do
      get "activate"
      put "activate"
      get "accept"
      put "accept"
      get "reject"
      put "reject"
      get "withdraw"
      put "withdraw"
    end
  end
  match "/offers/:owner_id/list" => "offers#index",  :via => :get

  resources :users
  match 'profile'           => "users#show",    :via => :get
  match "/users/:id/delete" => "users#delete",  :via => :get

  resources :activities
  
  resources :messages
  
  resources :sessions
  match "signin"          => "sessions#signin_get",     :via => :get
  match "signin"          => "sessions#signin_post",    :via => :post
  match "signup"          => "sessions#signin_post",    :via => :post
  match "signout"         => "sessions#destroy",        :via => :delete
  match "sessions/cancel" => "sessions#cancel",         :via => :post
  
  resources :identities do 
    member do
      get "delete"
      get "init"
      get "failure"
      post "success"
    end
  end

  match 'auth/:provider/init'     => 'identities#init'
  match 'auth/:provider/callback' => 'identities#success'
  match 'auth/failure'            => 'identities#failure'

  resources :deferred_actions, :only => [:show]
  match 'act'             => 'deferred_actions#show'
  match 'confirm'         => 'deferred_actions#confirm'
  match 'reset_password'  => 'deferred_actions#reset_password'
  
  
  match '/404' => 'errors#not_found'
  match '/422' => 'errors#unprocessable_entity'
  match '/500' => 'errors#internal_server_error'

  root :to => 'home#index'

end

app/models/identity.rb
# encoding: UTF-8

# stores a user's identity.
#
# An identity is needed to
# 
# - interact with a specific identity provider (e.g. an Identity::Twitter
#   object contains all information needed to post to twitter on a
#   user's behalf), and  
# - to verify a certain level of user identification (e.g. to post
#   or to reply to a quest a user must (probably) have an email
#   identity.
#
# There are specific subclasses:
#
# - Identity::Twitter
# - Identity::Facebook
# - Identity::Email
# - Identity::Address
# - Identity::Deleted
#
class Identity < ActiveRecord::Base
  belongs_to :user
  
  validates_presence_of :user, :on => :save
  
  after_create :create_user_if_missing
  after_create :reward_user
  
  after_destroy :soft_delete_user

  serialize :serialized, Hash
  attr_accessor   :delete_me, :accept_terms
  attr_accessible :commercial, :accept_terms
  
  #
  # returns the identities covered by OmniAuth
  def self.oauth_identities
    self.subclasses.map{ |i| i.name.split("::").last.downcase.to_sym } - [:deleted, :email, :address]
  end

  def self.provider(provider)
    expect! provider => Symbol
    
    self.subclasses.detect{ |i| i.name.split("::").last.downcase.to_sym == provider}
  end
  
  def self.find_user(attributes={})
    expect! attributes => Hash
    
    if (email = attributes[:email]) && (identity = where(:email => email).first) 
      identity.user
    end
  end

  def provider
    self.class.name.split("::").last.downcase.to_sym
  end
  
  def solitary?
    user.identities == [self]
  end
  
  # 
  # checks if the identity is ready to be further processed
  # e.g. all preconditions are fullfilled to start the oauth dance
  def processable?
    return true if self.user && !self.user.new_record?

    # clean error on accept_terms
    self.errors.delete(:accept_terms)
    
    # check if terms of use have been accepted
    self.errors.add(:accept_terms, :accepted) if self.accept_terms.to_i.zero?
    
    self.errors.blank?
  end
  
  protected
  
  def soft_delete_user
    return unless user && solitary?
    
    user.soft_delete!
  end

  def create_user_if_missing
    return if self.user
  
    user = User.new 
    user.identities << self
    user.save!
  end
  
  def reward_user
    user.reward_for(self)
  end
  
end

app/controllers/identities_controller.rb
# encoding: UTF-8

class IdentitiesController < ApplicationController
  before_filter :set_identity, :except => [:new, :create, :init, :success, :failure]
  before_filter :set_identity_params
  before_filter :set_provider
  
  def new
    # render the new modal dialoge of the requested identity
    @identity = Identity.provider(@provider).new
    render :layout => 'dialog'
  end
  
  def create
    @identity = Identity.provider(@provider).new(@identity_params)
    @identity.user = current_user || Identity.find_user(@identity_params)
    
    return unless @identity.save

    # if the identity was requested to perform another action
    # we have to call identity_presented! to trigger it's on susscess callback 
    return identity_presented! if identity_requested?(@provider)
    
    flash[:success] = I18n.t("notice.add.success", :record => @identity.class.model_name.human)
    redirect_to!(user_path(@identity.user))
  end

  def edit
    render :layout => 'dialog'
  end
  
  def update 
    # identity email updates have to be handled differently since
    # it has to be confirmed with user's current password
    return update_email if @identity.kind_of?(Identity::Email)

    @identity.attributes = @identity_params
    if @identity.save
      flash[:success] = I18n.t("notice.update.success", :record => @identity.class.model_name.human)
      redirect_to! @user
    end
  end

  def delete
    render :layout => 'dialog'
  end
  
  def destroy
    raise RuntimeError, "Identity #{@provider} is the only identity of user #{@user.inspect}"  if @identity.solitary?
    @identity.destroy
    
    flash[:success] = I18n.t("notice.remove.success", :record => "identity/#{@provider}".camelize.constantize.model_name.human)
    redirect_to! user_path(@user)
  end
  
  
  # --- Omniauth social identities actions ---------------------------------------------
  # The following actions initiate omniauth signups. It is an initiator
  # and callback of the OmniAuthMiddleware. 
  
  #
  # redirect to the given authentication provider
  # to perform the oauth dance for identities handled by OmniAuth
  def init
    # The OmniAuthMiddleware intercepts "/auth/" URLs, e.g. the "/auth/facebook" 
    # URL sets up and redirects to facebook auth. When Facebook oauth
    # returns to OmniAuthMiddleware, which then redirects to the "create" action.
    
    @identity = Identity.provider(@provider).new(@identity_params)
    @identity.user = current_user || (signin_identity && signin_identity.user)
    
    if @identity.processable?
      pre_process_signin # trigger pre processing
      redirect_to "/auth/#{@provider}"
    end
  end
  
  #
  # OmniAuthMiddleware receives the providers (successful) oauth infos and
  # redirects to the create action after the oauth dance is over.
  def success
    if (uid = request.env["omniauth.auth"].uid).present? && @provider.present?

      # At this point an existing user might have signed in for the first time,
      # or might just revisit the site. In the latter case we don't produce a flash message.
      flash[:success] = if current_user then  I18n.t("notice.add.success", :record => Identity.provider(@provider).new.class.model_name.human)
                        else                  I18n.t("sessions.auth.success")
                        end
      
      @identity = Identity.provider(@provider).find_or_create(uid, current_user || (signin_identity && signin_identity.user), request.env["omniauth.auth"])
      signin(User.find(@identity.user.id), @identity)
      post_process_signin # trigger post processing
      
      identity_presented!
    else
      flash[:error] = if current_user then  I18n.t("notice.add.error", :record => Identity.provider(@provider).new.class.model_name.human)
                      else                  I18n.t("sessions.auth.failure")
                      end
      identity_cancelled!
    end
  end
  
  # OmniAuthMiddleware receives the providers (unsuccessful) oauth and 
  # redirects to the failure action after the oauth dance is over.
  def failure
    flash[:error] = I18n.t("sessions.auth.failure")
    identity_cancelled!
  end
  
protected

  def set_identity
    @identity = Identity.find(params[:id])
    @user     = @identity.user
    raise(ArgumentErrorr, "Not allowed") unless current_user && @user == current_user
  end

  def set_identity_params
    @identity_params = if (identity_key = params.keys.detect{ |key| key.to_s.include?("identity_") })
        params[identity_key]
      else 
        {}
      end
  end
  
  def set_provider
    # provider is explicitly set in params
    @provider = params[:provider]
    
    # provider is given by identity
    @provider ||= @identity.provider if @identity

    # provider is given by identity key in params hash
    @provider ||= if (identity_key = params.keys.detect{ |key| key.to_s.include?("identity_") })
        identity_key.split("identity_").last
      end
      
    # provider is set in request by omniauth
    @provider ||= request.env["omniauth.auth"] && request.env["omniauth.auth"].provider
    
    # return symbolized provider if present
    @provider = @provider.to_sym if @provider.present?
  end
  
  def pre_process_signin
    # store the form data in the session, to be handled after oauth signin
    session[:identity_params] = @identity_params
    
    # trigger provider specific pre-processing
    self.send("pre_process_#{@provider}_signin") if self.respond_to?("pre_process_#{@provider}_signin")
  end
  
  def post_process_signin
    # fetch the form data provided by the user before oauth signin
    @identity_params = @identity_params.merge(session.delete(:identity_params) || {}).with_indifferent_access
    
    # set identity's commercial flag
    @identity.update_attributes(:commercial => true) if @identity_params[:commercial]
    
    # trigger provider specific post-processing
    self.send("post_process_#{@provider}_signin") if self.respond_to?("post_process_#{@provider}_signin")
  end
  
  def post_process_twitter_signin
    # handle user provides email adress
    if @identity_params[:email].present? && @identity.email != @identity_params[:email]
      @identity.update_attributes(:email => @identity_params[:email])
    end
    
    # handle user wants to folllow bountyhermes
    if @identity_params[:follow_bountyhermes].present?
      @identity.follow
      @identity.direct_message I18n.t("tweet.follow.success")
    end
  end
  
  def update_email
    if params[:reset] || Identity::Email.authenticate(@identity.email, @identity_params[:password])
      if @identity.update_attributes(
          :password               => @identity_params[:password_new],
          :password_confirmation  => @identity_params[:password_new_confirmation])
        flash[:success] = I18n.t("notice.update.success", :record => Identity::Email.human_attribute_name(:password))
        redirect_to! user_path(@user)
      else
        @identity.errors.add :password_new, @identity.errors.delete(:password).last
      end
    else
      @identity.errors.add :password, I18n.t("notice.password.invalid")
    end
  end
end

app/views/identities/_by_email.html.erb
<%= form_for @identity do |form| %>
  <%= hidden_field_tag :req, params[:req] %>
  <fieldset>
    <legend><%= I18n.t(:"signup.bountyhill")%></legend>
    <%= form.error_messages :scope => "signup" %>

    <%= form.control_group :name %>
    <%= form.control_group :email %>
    <%= form.control_group :password,               :password_field %>
    <%= form.control_group :password_confirmation,  :password_field %>

    <%= form.agree_to_terms %>

    <div class="form-actions">
      <%= link_to I18n.t(:go_to_signin), signin_path(:req => params[:req]) %>
      <%= form.submit I18n.t(:sign_up), :class => "btn btn-primary" %>
    </div>
  </fieldset>
<% end %>

app/views/identities/create.js.erb
$("#<%= @provider %>").html("<%= escape_javascript(partial("identities/#{@provider}/new", :identity => @identity)) %>");

app/views/identities/delete.html.erb
<% modal_dialog I18n.t("identity/#{@provider}.form.delete.title"), :html => { :class => @provider } do %>
  <% modal_body :html => { :id => @provider } do %>
  
    <%= form_for(@identity, :url => identity_url(@identity), :method => :delete) do |form| %>
      <p><%= I18n.t("identity/#{@provider}.form.delete.legend") %></p>
      <%= form.control_group :delete_me, :check_box %>

      <%= form.actions "#", 
        :label          => I18n.t("button.remove"),
        :name           => "delete_#{@provider}",
        :id             => "delete_#{@provider}",
        :class          => "btn btn-danger",
        :disabled       => "disabled",
        :"data-dismiss" => "modal" %>
    <% end %>

    <script type="text/javascript" charset="utf-8">
      $("#identity_<%= @provider %>_delete_me").change(function() {
        if($(this).is(':checked'))
          $("#delete_<%= @provider %>").removeAttr("disabled");
        else
          $("#delete_<%= @provider %>").attr("disabled", "disabled");
      });
    </script>
    
  <% end %>
<% end %>

app/views/identities/edit.html.erb
<% modal_dialog I18n.t("identity/#{@provider}.form.edit.title"), :html => { :class => @provider } do %>
  <% modal_body :html => { :id => @provider } do %>
    <%= partial("identities/#{@provider}/edit", :identity => @identity) %>
  <% end %>
<% end %>

app/views/identities/init.js.erb
$("#<%= @provider %><%= ' .accordion-inner' unless current_user %>").html("<%= escape_javascript(partial("identities/#{@provider}/new", :identity => @identity)) %>");

app/views/identities/new.html.erb
<% modal_dialog I18n.t("identity/#{@provider}.form.new.title"), :html => { :class => @provider } do %>
  <% modal_body :html => { :id => @provider } do %>
    <%= partial("identities/#{@provider}/new", :identity => @identity) %>
  <% end %>
<% end %>

app/views/identities/show.html.erb
<% provide(:title, I18n.t(:profile)) %>
<div class="hero-unit">
  <%= gravatar_for @identity %>
  <h1><%= @identity.name %></h1>
</div

app/views/identities/update.js.erb
$("#<%= @provider %>").html("<%= escape_javascript(partial "identities/#{@provider}/edit", :identity => @identity) %>");